defmodule LiveRender.Format.A2UI do
  @moduledoc """
  A2UI (Agent-to-User Interface) format adapter.

  Translates between Google's [A2UI protocol](https://github.com/google/A2UI) and
  LiveRender's internal spec format. This enables LiveRender to consume A2UI JSONL
  streams — either generated by an LLM or received from an A2UI-speaking agent
  via A2A, AG UI, or any other transport.

  ## A2UI message types

  The adapter handles these server-to-client envelope messages:

  - `createSurface` — initializes a new surface (spec)
  - `updateComponents` — adds/updates components in the flat element map
  - `updateDataModel` — patches the data model (state)
  - `deleteSurface` — clears the spec

  ## Component mapping

  A2UI components use PascalCase names (`Text`, `Card`, `Column`). These are
  converted to the snake_case types used in the LiveRender catalog (`text`,
  `card`, `column`). When a catalog is provided via `stream_init/1` opts,
  the adapter builds an exact PascalCase→snake_case map from the registered
  components, falling back to naive conversion for unknown types.

  ## Data binding

  A2UI data bindings (`{"path": "/foo/bar"}`) are automatically converted to
  LiveRender's `{"$state": "/foo/bar"}` expressions during component ingestion.
  """

  @behaviour LiveRender.Format

  alias LiveRender.Format.OpenUILang.Compiler
  alias LiveRender.Format.Shared

  @impl true
  def prompt(component_map, actions, opts) do
    custom_rules = Keyword.get(opts, :custom_rules, [])

    """
    You generate UI using the A2UI protocol. Use ONLY these components and actions.

    #{format_section()}
    #{signatures_section(component_map)}
    #{Shared.actions_section(actions)}#{Shared.rules_section(custom_rules)}\
    """
    |> String.trim()
  end

  @impl true
  def parse(text, opts \\ []) do
    name_map = build_name_map(catalog_from_opts(opts))

    case extract_fence(text) do
      {:ok, content} -> parse_jsonl(content, name_map)
      :none -> try_raw_jsonl(text, name_map)
    end
  end

  @impl true
  def stream_init(opts \\ []) do
    catalog = catalog_from_opts(opts)

    %{
      buffer: "",
      in_fence: false,
      spec: empty_spec(),
      name_map: build_name_map(catalog)
    }
  end

  @impl true
  def stream_push(state, chunk) do
    Shared.stream_push(state, chunk, &process_fence_buffer/2)
  end

  @impl true
  def stream_flush(state) do
    if state.in_fence and state.buffer != "" do
      buf = state.buffer <> "\n"
      {lines, _} = Shared.split_lines(buf)
      {state, events} = process_lines(state, lines)
      {%{state | buffer: "", in_fence: false}, events}
    else
      {state, []}
    end
  end

  # --- Fence processing ---

  defp process_fence_buffer(state, buf) do
    {lines, remainder} = Shared.split_lines(buf)
    {state, events} = process_lines(%{state | buffer: ""}, lines)
    {%{state | buffer: remainder}, events}
  end

  defp process_lines(state, lines) do
    Enum.reduce(lines, {state, []}, fn line, {st, evts} ->
      process_single_line(st, evts, String.trim(line))
    end)
  end

  defp process_single_line(state, events, "```") do
    {%{state | in_fence: false}, events}
  end

  defp process_single_line(state, events, "") do
    {state, events}
  end

  defp process_single_line(state, events, line) do
    case Jason.decode(line) do
      {:ok, envelope} ->
        new_spec = apply_envelope(state.spec, envelope, state.name_map)

        if new_spec != state.spec do
          {%{state | spec: new_spec}, events ++ [{:spec, new_spec}]}
        else
          {state, events}
        end

      _ ->
        {state, events}
    end
  end

  # --- One-shot parsing ---

  defp extract_fence(text) do
    Shared.extract_fence(text)
  end

  defp parse_jsonl(content, name_map) do
    spec =
      content
      |> String.split("\n")
      |> Enum.reduce(empty_spec(), fn line, spec ->
        line = String.trim(line)

        case Jason.decode(line) do
          {:ok, envelope} -> apply_envelope(spec, envelope, name_map)
          _ -> spec
        end
      end)

    {:ok, spec}
  end

  defp try_raw_jsonl(text, name_map) do
    trimmed = String.trim(text)

    if String.starts_with?(trimmed, "{") do
      parse_jsonl(trimmed, name_map)
    else
      {:ok, %{}}
    end
  end

  # --- Envelope handling ---

  defp apply_envelope(_spec, %{"createSurface" => _}, _name_map) do
    empty_spec()
  end

  defp apply_envelope(spec, %{"updateComponents" => %{"components" => components}}, name_map) do
    Enum.reduce(components, spec, &ingest_component(&2, &1, name_map))
  end

  defp apply_envelope(spec, %{"updateDataModel" => update}, _name_map) do
    path = Map.get(update, "path", "/")
    value = Map.get(update, "value")
    apply_data_model_update(spec, path, value)
  end

  defp apply_envelope(_spec, %{"deleteSurface" => _}, _name_map) do
    empty_spec()
  end

  defp apply_envelope(spec, _unknown, _name_map), do: spec

  # --- Component ingestion ---

  @reserved_keys ~w(id component children child accessibility)

  defp ingest_component(spec, %{"id" => id, "component" => component} = comp, name_map) do
    type = Map.get(name_map, component, Compiler.to_snake_case(component))
    children = extract_children(comp)
    props = extract_props(comp)

    element = %{"type" => type, "props" => props, "children" => children}

    spec = put_in(spec, ["elements", id], element)

    if id == "root" and is_nil(spec["root"]) do
      Map.put(spec, "root", "root")
    else
      spec
    end
  end

  defp ingest_component(spec, _invalid, _name_map), do: spec

  defp extract_children(comp) do
    cond do
      is_list(comp["children"]) -> comp["children"]
      is_binary(comp["child"]) -> [comp["child"]]
      is_list(comp["tabs"]) -> Enum.map(comp["tabs"], & &1["child"]) |> Enum.reject(&is_nil/1)
      true -> []
    end
  end

  defp extract_props(comp) do
    comp
    |> Map.drop(@reserved_keys)
    |> convert_data_bindings()
  end

  defp convert_data_bindings(%{"path" => path} = value)
       when is_binary(path) and map_size(value) == 1 do
    %{"$state" => path}
  end

  defp convert_data_bindings(value) when is_map(value) do
    Map.new(value, fn {k, v} -> {k, convert_data_bindings(v)} end)
  end

  defp convert_data_bindings(value) when is_list(value) do
    Enum.map(value, &convert_data_bindings/1)
  end

  defp convert_data_bindings(value), do: value

  # --- Data model ---

  defp apply_data_model_update(spec, "/", value) when is_map(value) do
    Map.put(spec, "state", value)
  end

  defp apply_data_model_update(spec, "/" <> _ = path, value) do
    state = spec["state"] || %{}
    Map.put(spec, "state", LiveRender.StateResolver.put_in_path(state, path, value))
  end

  defp apply_data_model_update(spec, _path, _value), do: spec

  # --- Helpers ---

  defp empty_spec, do: %{"root" => nil, "elements" => %{}, "state" => %{}}

  defp build_name_map(component_map) do
    for {snake_name, _mod} <- component_map, into: %{} do
      {Compiler.to_pascal_case(snake_name), snake_name}
    end
  end

  defp catalog_from_opts(opts) do
    case Keyword.get(opts, :catalog) do
      nil -> %{}
      mod when is_atom(mod) -> mod.components()
      map when is_map(map) -> map
    end
  end

  # --- Prompt generation ---

  defp format_section do
    """
    ## Output format (A2UI JSONL)

    Output a stream of A2UI envelope messages inside a ```spec fence — one JSON object per line.

    1. Start with a `createSurface` message:
    {"version":"v0.10","createSurface":{"surfaceId":"main","catalogId":"basic"}}

    2. Send components with `updateComponents` (flat list, referenced by ID):
    {"version":"v0.10","updateComponents":{"surfaceId":"main","components":[{"id":"root","component":"Column","children":["heading","card"]},{"id":"heading","component":"Text","text":"Dashboard","variant":"h2"},{"id":"card","component":"Card","child":"content"},{"id":"content","component":"Text","text":"Hello world"}]}}

    3. Send data with `updateDataModel`:
    {"version":"v0.10","updateDataModel":{"surfaceId":"main","path":"/user","value":{"name":"Alice"}}}

    Data binding: use {"path":"/data/key"} for any prop that should read from the data model.

    Rules:
    - Component names use PascalCase (Text, Card, Column, Row)
    - One component MUST have id "root" — it is the entry point of the UI tree
    - Children are referenced by ID string, never defined inline
    - Use `children` (array) for multiple children, `child` (string) for a single child
    - You may send multiple `updateComponents` messages to stream progressively
    """
  end

  defp signatures_section(component_map) do
    signatures =
      component_map
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map_join("\n", &format_signature/1)

    """
    ## Components

    #{signatures}
    """
  end

  defp format_signature({_snake, mod}) do
    meta = mod.__component_meta__()
    pascal = Compiler.to_pascal_case(meta.name)
    schema = mod.json_schema()
    required = Map.get(schema, "required", [])
    properties = Map.get(schema, "properties", %{})

    props_doc =
      properties
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map_join(", ", fn {name, prop} ->
        req = if name in required, do: "", else: "?"
        type_hint = format_prop_type(prop)
        "#{name}#{req}#{type_hint}"
      end)

    children_hint =
      if :inner_block in meta.slots, do: " (has children)", else: ""

    desc = if meta.description != "", do: " — #{meta.description}", else: ""
    "- `#{pascal}` #{props_doc}#{children_hint}#{desc}"
  end

  defp format_prop_type(%{"enum" => values}) do
    ": " <> Enum.map_join(values, "|", &inspect/1)
  end

  defp format_prop_type(%{"type" => "array"}), do: ": array"
  defp format_prop_type(%{"type" => "integer"}), do: ": int"
  defp format_prop_type(%{"type" => "number"}), do: ": number"
  defp format_prop_type(%{"type" => "boolean"}), do: ": bool"
  defp format_prop_type(_), do: ""
end
